# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'MacTransit' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Sparkle'
  pod 'SwiftBus', :path => './SwiftBus'

  # Pods for MacTransit

  target 'MacTransitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MacTransitUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
