source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SwiftBus_Example' do
  pod "SwiftBus", :path => "../"
end

target 'SwiftBus_Tests' do
  pod "SwiftBus", :path => "../"
end

target 'SwiftBus Watch Example Extension' do
  platform :watchos, '2.0'
  pod "SwiftBus", :path => "../"
end
