# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

use_frameworks!
target 'MuniMenuBar' do
  pod 'SWXMLHash', '~> 1.1.0'
  pod 'Sparkle', '~> 1.10'
end

target 'MuniMenuBarTests' do

end

