# Uncomment this line to define a global platform for your project
platform :osx, '10.10'

use_frameworks!
target 'MuniMenuBar' do
  pod 'SWXMLHash', '~> 1.1.0'
end

target 'MuniMenuBarTests' do

end

