# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

use_frameworks!
target 'MuniMenuBar' do
  pod 'SWXMLHash', '~> 2.0.0'
  pod 'Sparkle'
end

target 'MuniMenuBarTests' do

end

