# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

target 'TransitBar' do
  pod 'Crashlytics'
  pod 'Sparkle'
  pod 'SwiftBus', :path => './SwiftBus'
end

target 'TransitBar AppStore' do
  pod 'Crashlytics'
  pod 'SwiftBus', :path => './SwiftBus'
end

