# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

target 'MacTransit' do
  pod 'Sparkle'
  pod 'SwiftBus', :path => './SwiftBus'
end

target 'MacTransit AppStore' do
  pod 'SwiftBus', :path => './SwiftBus'
end

